### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by rubuy-74** [NIAEFEUP/website-ae#33]
Links Organization for header:
0. Página Inicial
1. AEFEUP
	Quem Somos
	História da AEFEUP
	Cedências de Espaço
	Serviços
	Eventos
	Núcleos e Associações
	Documentos
2. Estudante
	Bem-vindo à FEUP
	Guia do Estudante (+ Links úteis)
	Espaços
	Oportunidades
	Apoio Social e Bem-estar
3. Desporto
	Seleções
	História e Troféus
	Motorsport (fsfeup and msfeup/motor student)
4. Loja
5. Contactos

Mockup Footer:
![image](https://github.com/user-attachments/assets/b19056a1-2e34-4f63-bcad-66e6eb8f3f0b)

**Comment by thePeras** [comment]
For the footer sponsors, I suggest leaving them just in the landing page
